config/routes.rb
Rails.application.routes.draw do

  resources :student_modules
  resources :course_modules
  resources :lecturers
  devise_for :students

  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'

  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_module.rb
class StudentModule < ApplicationRecord
  # Validates the course module so that the user cannot add the same course module twice
  validates :course_module, uniqueness: true

  # association between Student Module and Course Module
  # A Student Module belongs to a course module
  belongs_to :course_module

  # Association between Student Module and Student
  # A student module belongs to a student.
  belongs_to :student
end

app/controllers/student_modules_controller.rb
class StudentModulesController < ApplicationController
  before_action :set_student_module, only: [:show, :edit, :update, :destroy]
  #Authenticate the user before letting them call any of the methods in this class
  before_action :authenticate_student!

  # GET /student_modules
  # GET /student_modules.json
  # This method gets all the student's modules
  def index
    @student_modules = StudentModule.all
  end

  # GET /student_modules/1
  # GET /student_modules/1.json
  def show
  end

  # GET /student_modules/new
  # This method lets a student module model be initialized
  def new
    @student_module = StudentModule.new
  end

  # GET /student_modules/1/edit
  def edit
  end

  # POST /student_modules
  # POST /student_modules.json
  # This method lets a student module model be added into the database
  def create
    @student_module = StudentModule.new(student_module_params)
    respond_to do |format|
      if @student_module.save
        format.html { redirect_to @student_module, notice: 'Student module was successfully created.' }
        format.json { render :show, status: :created, location: @student_module }
      else
        format.html { render :new }
        format.json { render json: @student_module.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /student_modules/1
  # PATCH/PUT /student_modules/1.json
  def update
    respond_to do |format|
      if @student_module.update(student_module_params)
        format.html { redirect_to @student_module, notice: 'Student module was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_module }
      else
        format.html { render :edit }
        format.json { render json: @student_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_modules/1
  # DELETE /student_modules/1.json
  # This method lets the user delete the student module object shown on the UI
  def destroy
    @student_module.destroy
    respond_to do |format|
      format.html { redirect_to student_modules_url, notice: 'Student module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_module
      @student_module = StudentModule.find(params[:id])
    end

    # Set which parameters can go in
    def student_module_params
      params.require(:student_module).permit(:course_module_id, :student_id)
    end
end

app/helpers/student_modules_helper.rb
module StudentModulesHelper
end

app/views/student_modules/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@student_module) do |f|

  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :course_module
    = f.hidden_field :student_id, :value => current_student.id

  .form-actions
    %button= f.submit "Add Module"

app/views/student_modules/edit.html.haml
%h1 Editing student_module

= render 'form'

= link_to 'Show', @student_module
\|
= link_to 'Back', student_modules_path

app/views/student_modules/index.html.haml
%h1 Your Modules

:javascript
  $('input').click(function(){
      $('td:contains("No")').parent().toggle();
  });

%table{style: "text-align: center; margin-left: auto; margin-right:auto;"}
  %thead
    %tr
      %th Module
      %th Student
      %th Credits
      %th Semester

  %tbody
    - @student_modules.each do |student_module|
      - if student_signed_in?
        - if student_module.student.name == current_student.name
          %tr
            %td= student_module.course_module.name
            %td= student_module.student.name
            %td= student_module.course_module.credits
            %td= student_module.course_module.semester
            %td= link_to 'Delete', student_module_path(student_module), method: :delete, data: { confirm: 'Are you sure?' }



- if student_signed_in?
  - totalCredits = 0
  - @student_modules.each do |student_module|
    - if student_module.student.name == current_student.name
      - totalCredits = totalCredits + student_module.course_module.credits

%h2= "Total Credits = #{totalCredits}"


%br

%h2{style: "display: flex;align-items: center;justify-content: center;"}= link_to 'Add a new Module', new_student_module_path

app/views/student_modules/new.html.haml
%h1 Add Module

= render 'form'

%h2= link_to "Back", student_modules_path, class: "button"

app/views/student_modules/show.html.haml
%p#notice= notice

%p
  %b Module:
  = @student_module.course_module.name
%p
  %b Student:
  = @student_module.student.name

= link_to 'Edit', edit_student_module_path(@student_module)
\|
= link_to 'Back', student_modules_path