config/routes.rb
Rails.application.routes.draw do

  resources :student_modules
  resources :course_modules
  resources :lecturers
  devise_for :students

  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'

  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/course_module.rb
class CourseModule < ApplicationRecord

  # Each course belongs to a lecturer as it cannot have more than one lecturer
  belongs_to :lecturer
end

app/controllers/course_modules_controller.rb
class CourseModulesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_student!

  # GET /course_modules
  # GET /course_modules.json
  def index
    @course_modules = CourseModule.all
  end

  # GET /course_modules/1
  # GET /course_modules/1.json
  def show
  end

  # GET /course_modules/new
  def new
    @course_modules = CourseModule.new
  end

  # GET /course_modules/1/edit
  def edit
  end

  # POST /course_modules
  # POST /course_modules.json
  # def create
  #   @course_modules = CourseModule.new(course_params)
  #
  #   respond_to do |format|
  #     if @course_modules.save
  #       format.html { redirect_to @course_modules, notice: 'Course was successfully created.' }
  #       format.json { render :show, status: :created, location: @course_modules }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @course_modules.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /course_modules/1
  # PATCH/PUT /course_modules/1.json
  def update
    respond_to do |format|
      if @course_modules.update(course_params)
        format.html { redirect_to @course_modules, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_modules }
      else
        format.html { render :edit }
        format.json { render json: @course_modules.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_modules/1
  # DELETE /course_modules/1.json
  # def destroy
  #   @course_modules.destroy
  #   respond_to do |format|
  #     format.html { redirect_to course_modules_url, notice: 'Course was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course_modules = CourseModule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :code, :lecturer_id)
    end
end

app/views/course_modules/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :code
    = f.association :lecturer

  .form-actions
    = f.button :submit

app/views/course_modules/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', course_modules_path

app/views/course_modules/index.html.haml
%h1 Select Modules

:javascript
  function search() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[0];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }

%br/
%input#myInput{onkeyup: "search()", placeholder: "Search for module name", title: "Type in a name", type: "text", style: "margin-left: 850px;"}/
%br/
%table#myTable{style: "text-align: center; margin-left: auto; margin-right:auto;"}
  %thead
    %tr
      %th Name
      %th Code
      %th Credits
      %th Semester
      %th Lecturer
  %tbody
    - @course_modules.each do |course|
      %tr
        %td= course.name
        %td= course.code
        %td= course.credits
        %td= course.semester
        %td= course.lecturer.name
        %td= link_to 'Show  ', course
        %td= link_to 'Add', new_student_module_path

-# %br
-#
-# %h1 Semester 2
-# %table{style: "text-align: center; margin-left: auto; margin-right:auto;"}
-#   %thead
-#     %tr
-#       %th Name
-#       %th Code
-#       %th Credits
-#       %th Semester
-#       %th Lecturer
-#
-#   %tbody
-#     - @course_modules.each do |course|
-#       - if course.semester == 2
-#         %tr
-#           %td= course.name
-#           %td= course.code
-#           %td= course.credits
-#           %td= course.semester
-#           %td= course.lecturer.name
-#           %td= link_to 'Show  ', course
-#           %td= link_to 'Add', new_student_module_path
-#
-# %br

app/views/course_modules/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', course_module_path

app/views/course_modules/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @course_modules.name
%p
  %b Code:
  = @course_modules.code
%p
  %b Lecturer:
  = @course_modules.lecturer.name

%p
  %b Semester:
  = @course_modules.semester

%p
  %b Credits:
  = @course_modules.credits
  %br/
  %br/
  = link_to 'Edit', edit_course_module_path(@course_modules)
  \|
  = link_to 'Add Module', new_student_module_path(@course_modules)
  \|
  = link_to 'Back', course_modules_path