config/routes.rb
Rails.application.routes.draw do

  resources :student_modules
  resources :course_modules
  resources :lecturers
  devise_for :students

  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'

  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home

  end

  def contact

  end

  # This method is used to
  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    # Checks whether email field is blank or not, if it is not then it will send
    # an email to the user. If the field is blank then it will alert the user that
    # an email is required
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
  end


end

app/views/home/contact.html.haml
%h1=t('.title')
%p=t('.contact_us')

= form_tag request_contact_path, method: 'post' do
  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size: 50

  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')

  = label_tag :telephone, t('.telephone')
  = telephone_field_tag :telephone, '', title: t('.enter_telephone')

  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100

  = submit_tag t('.submit')

app/views/home/home.html.haml
%h1=t('.title')
%h2=t('.welcome')
- if student_signed_in?
  %h2="Hello #{current_student.name}"
=link_to "Add Module", course_modules_path, class: "button btn"
=link_to "View My Modules", student_modules_path, class: "button btn"