config/routes.rb
Rails.application.routes.draw do

  resources :student_modules
  resources :course_modules
  resources :lecturers
  devise_for :students

  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'

  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lecturer.rb
class Lecturer < ApplicationRecord
  # A lecturer may have more than one module to teach
  # This is the association used between Lecturer and CourseModule
  has_many :course_modules
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/views/lecturers/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@lecturer) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/lecturers/edit.html.haml
%h1 Editing lecturer

= render 'form'

= link_to 'Show', @lecturer
\|
= link_to 'Back', lecturers_path

app/views/lecturers/index.html.haml
%h1 Listing lecturers

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @lecturers.each do |lecturer|
      %tr
        %td= lecturer.name
        %td= link_to 'Show', lecturer
        %td= link_to 'Edit', edit_lecturer_path(lecturer)
        %td= link_to 'Destroy', lecturer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lecturer', new_lecturer_path

app/views/lecturers/new.html.haml
%h1 New lecturer

= render 'form'

= link_to 'Back', lecturers_path

app/views/lecturers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @lecturer.name

= link_to 'Edit', edit_lecturer_path(@lecturer)
\|
= link_to 'Back', lecturers_path